import './js/for-each-partial/book-list';
import './js/for-each-partial/categories';
import './js/for-each-partial/header';
import './js/for-each-partial/modal';
import './js/for-each-partial/store';
import './js/for-each-partial/support';
import './js/api/book.service';
import './js/for-each-partial/footer-modal';
import './js/for-each-partial/footer-photo';
